DROP TABLE IF EXISTS bill_old_gold;

ALTER TABLE bills DROP COLUMN IF EXISTS type;
ALTER TABLE bills DROP COLUMN IF EXISTS status;
ALTER TABLE bills DROP COLUMN IF EXISTS old_gold_amount;
ALTER TABLE bills DROP COLUMN IF EXISTS advance_amount;
ALTER TABLE bills DROP COLUMN IF EXISTS balance_due;
